<a href="https://colab.research.google.com/github/vedikapathak43-ai/Data_Science_70/blob/main/Practical_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from IPython.display import display, HTML

# Function to display tables in center
def display_centered(df):
    display(HTML("<div style='display:flex; justify-content:center'>" + df.to_html() + "</div>"))

# 1. Load the dataset
df = pd.read_csv('online vs store shopping dataset.csv')

print("\n========== DATASET PREVIEW ==========\n")
display_centered(df.head())

# 2. Filtering: Select shoppers with high monthly income (>100000)
high_income_shoppers = df[df['monthly_income'] > 100000]

print("\n========== FILTERED DATA (High Income Shoppers) ==========\n")
display_centered(high_income_shoppers.head())

# 3. Grouping & Aggregate Statistics
stats = df.groupby('shopping_preference')['avg_online_spend'].agg(['sum','mean','count','min','max'])

print("\n========== AGGREGATE STATISTICS ==========\n")
display_centered(stats)

========== DATASET PREVIEW ==========

========== FILTERED DATA (High Income Shoppers) ==========

========== AGGREGATE STATISTICS ==========